config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root 'home#index'
  devise_for :users
  resources :categories
  resources :tasks
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
    validates :name, presence: true, uniqueness: true
    has_many :tasks, :dependent => :destroy
    belongs_to :user
end

app/models/task.rb
class Task < ApplicationRecord
    validates :category_id, :name, :category, :deadline, :body, presence: true
    belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
   validates :password, presence: true, confirmation: true
  has_many :categories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name, :description, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :set_task
  before_action :set_categories
  def index
  end

  def set_task
    @tasks = Task.all 
  end

  def set_categories
    if user_signed_in?
      @categories = current_user.categories
    end
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action :set_categories

  # GET /tasks or /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1 or /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks or /tasks.json
  def create
    @task = Task.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to task_url(@task), notice: "Task was successfully created." }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1 or /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to task_url(@task), notice: "Task was successfully updated." }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1 or /tasks/1.json
  def destroy
    @task.destroy

    respond_to do |format|
      format.html { redirect_to tasks_url, notice: "Task was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def task_params
      params.require(:task).permit(:name, :body, :deadline, :category_id)
    end

    def set_categories
      @categories = current_user.categories
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def resource_name
        :user
      end
    
      def resource_class 
         User 
      end
    
      def resource
        @resource ||= User.new
      end
    
      def devise_mapping
        @devise_mapping ||= Devise.mappings[:user]
      end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>" class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title lead"><strong><h5><%= link_to category.name, category, class:"text-decoration-none text-dark"%></h5></strong>
    <p class="card-text"><%= category.description %></p>
  </div>
  <ul class="list-group list-group-flush">
    <% category.tasks.each do |task| %>
      <li class="list-group-item">
      <%= link_to task.name, task, class:"text-decoration-none text-dark" %>
      </li>
    <%end%>
  </ul>
  <div class="card-body">
  <%= link_to "", new_task_path,  class:"bbi bi-plus-circle-fill h3" %>
    
  </div>
</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block", class:"form-label" %>
    <%= form.text_field :name, class:"form-control" %>
  </div>

  <div>
    <%= form.label :description, style: "display: block", class:"form-label mt-3" %>
    <%= form.text_area :description, class:"form-control" %>
  </div>

  <div>
    <%= form.number_field :user_id, id: :category_user_id, value: current_user.id, type: :hidden%>
  </div>
  <br>
  <div>
    <%= form.submit class:"btn btn-primary mt-2" %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to Journal", categories_path %>
</div>

app/views/categories/index.html.erb
<h1 class="display-6 text-center">Journal</h1><br>
<div class="container d-flex justify-content-evenly flex-row">
<div id="categories">
  <% @categories.each do |category| %>
      <% if category.user == current_user %>
        <%= render category %>
        <br>
      <% end %>
  <% end %>
</div>
</div>

app/views/categories/new.html.erb
<h1 class="display-6">New Task Category</h1>


<%= render "form", category: @category %>

<br>

<div>

</div>

app/views/categories/show.html.erb
<%= render @category %>

<div>
  <%= link_to "Edit this category", edit_category_path(@category), class:"btn btn-primary mt-3" %>
  <%= link_to "Back to Journal", categories_path, class:"btn btn-secondary mt-3" %>

  <%= button_to "Destroy this category", @category, method: :delete, class:"btn btn-warning mt-3" %>
</div>

app/views/home/_header.html.erb
<header class="p-3 mb-3 border-bottom">
  <div class="container">
    <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
      <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-dark text-decoration-none">
        <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>
      </a>

      <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
        <li class="nav-item"><%= link_to "Home", root_path, class:"nav-link px-2 link-dark"%></li>
        
          <% if user_signed_in? %>
          <li class="nav-item"><%= link_to "Journal", categories_path, class:"nav-link px-2 link-dark"%></li>
          <li class="nav-item"><%= link_to "Tasks", tasks_path, class:"nav-link px-2 link-dark" %></li>
          <li class="nav-item"><%= link_to "Add category",  new_category_path, class:"nav-link px-2 link-dark" %></li>
          <% else %>
          <li><a href="#" class="nav-link px-2 link-dark">Overview</a></li>
          <% end %>
      </ul>

      <div class="text-end d-flex">

        <% if user_signed_in? %>
          <%= current_user.email %>
          <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle ms-2" data-bs-toggle="dropdown" aria-expanded="false">
              <img src="https://github.com/mdo.png" alt="mdo" width="32" height="32" class="rounded-circle">
            </a>
            <ul class="dropdown-menu text-small">
               <li><%= link_to "Edit Profile", edit_user_registration_path, class:"dropdown-item" %></li>
              <li><hr class="dropdown-divider"></li>
               <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete, class:"dropdown-item text-black" %></li>
            </ul>
                     
        <% else %>
          <button type="button" class="btn btn-outline-dark me-2"><%= link_to "Login", new_user_session_path, class:"nav-link" %></button>
          <button type="button" class="btn btn-warning"><%= link_to "Sign Up", new_user_registration_path, class:"nav-link text-black" %></button>
        <% end %>

      </div>
    </div>
  </div>
</header>

app/views/home/index.html.erb
<% if user_signed_in?%>
<div class="container">
    <h1 class="display-6 text-center">Today</h1>
    <div class="container d-flex justify-content-center flex-wrap">
    <% @tasks.each do |task| %>
        <% @categories.each do |category| %>
            <% if task.category_id == category.id %>
                <%if task.deadline.to_date == DateTime.current.to_date %>
                    <div class="card bg-light mb-3 ms-4" style="width: 250px">
                        <%= render task %>
                    </div>
                <% end %>
            <% end %>
        <% end %>
    <% end %>
    </div>



    <h1 class="display-6 text-center">Overdue</h1>
    <div class="container d-flex justify-content-center flex-wrap">
    <% @tasks.each do |task| %>
        <% @categories.each do |category| %>
            <% if task.category_id == category.id %>
                <%if task.deadline.to_date < DateTime.current.to_date %>
                    <div class="card border-danger mb-3 ms-4 text-danger" style="width: 250px">
                        <%= render task %>
                    </div>
                <% end %>
            <% end %>
        <% end %>
    <% end %>
    </div>


    <h1 class="display-6 text-center">Upcoming</h1>
    <div class="container d-flex justify-content-center flex-wrap">
    <% @tasks.each do |task| %>
        <% @categories.each do |category| %>
            <% if task.category_id == category.id %>
                <%if task.deadline.to_date > DateTime.current.to_date %>
                    <div class="card border-light mb-3 ms-4" style="width: 250px">
                        <%= render task %>
                    </div>
                <% end %>
            <% end %>
        <% end %>
    <% end %>
    </div>
</div>
<% else %>
<div class="container col-xxl-8 px-4 py-5">
    <div class="row flex-lg-row-reverse align-items-center g-5 py-5">
     <div class="col-md-10 mx-auto col-lg-5">
        <form class="p-4 p-md-5 border rounded-3 bg-light">
          <%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
          <div class="form-floating mb-3">
            <%= f.email_field :email, autofocus: true, autocomplete: "email", class:"form-control", placeholder:"name@example.com", id:"floatingPassword"%>
            <label for="floatingInput">Email address</label>
          </div>

          <div class="form-floating mb-3">
            <%= f.password_field :password, autocomplete: "current-password", class:"form-control", placeholder:"Password" %>
            <label for="floatingPassword">Password</label>
          </div>

          <div class="checkbox mb-3">
            <% if devise_mapping.rememberable? %>
            <div class="field">
              <%= f.check_box :remember_me %>
              <%= f.label :remember_me %>
            </div>
          <% end %>
          </div>
       <%= f.submit "Log in", class:"w-100 btn btn-lg btn-primary actions mb-3" %>
       <p class="text-center mt-2"><%= link_to "Forgot password?", new_user_password_path, method: :delete, class:"text-decoration-none" %></p>
          <hr class="my-4">
          <small class="text-muted">By clicking Login, you agree to the terms of use.</small>
            <% end %>
        </form>
        
      </div>
      <div class="col-lg-6">
        <h1 class="display-5 fw-bold lh-1 mb-3">Happy Journal</h1>
        <p class="lead">Join millions of users and create a healthier, happier mind. A sanctuary for your mind and soul, Journey will help increase your positive energy, be more grateful and a calmer mind by building healthy thinkings through journaling.</p>
        <p class="lead">We’re more than just a journal, or a diary; we’re your own motivational coach and happiness trainer. Let's embark on a fabulous journey of self-improvement today.</p>
        <div class="d-grid gap-2 d-md-flex justify-content-md-start">
          <button type="button" class="btn btn-primary btn-lg px-4 me-md-2">Explore</button>
          <button type="button" class="btn btn-outline-secondary btn-lg px-4">Download</button>
        </div>
      </div>
    </div>
  </div>

  <% end %>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Journal App</title>
    <%= stylesheet_link_tag "styles" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render 'home/header'%>
    <div class="container">
    <br/>
    <% if notice %>
      <%= render 'layouts/alerts'%>
    <% end %>
    
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task) do |form| %>
  <% if task.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label :category, style: "display: block", class:"form-label" %>
    <%= form.select :category_id, options_for_select(@categories.collect { |cat| [cat.name, cat.id]}), class:"form-control" %>
  </div>

  <div>
    <%= form.label :name, style: "display: block", class:"form-label" %>
    <%= form.text_field :name, class:"form-control" %>
  </div>

  <div>
    <%= form.label :description, style: "display: block", class:"form-label" %>
    <%= form.text_area :body, class:"form-control" %>
  </div>

  <div>
    <%= form.label :deadline, style: "display: block", class:"form-label" %>
    <%= form.datetime_field :deadline, class:"form-control" %>
  </div>


  <div>
    <%= form.submit class:"btn btn-primary mt-2" %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<div id="<%= dom_id task %>">

  <div class="card-header">
    <% if task.deadline.to_date - DateTime.current.to_date == 0%>
      <%= task.deadline.strftime('Today, %l:%M %p') %>
    <% elsif task.deadline.to_date-DateTime.current.to_date == 1%>
      <%= task.deadline.strftime('Tomorrow, %l:%M %p') %>
    <% elsif task.deadline.to_date-DateTime.current.to_date < 0 %>
      <%= task.deadline.strftime('%b %d %Y %l:%M %p') %>
    <% elsif task.deadline.to_date-DateTime.current.to_date < 7 %>
      <%= task.deadline.strftime('%A, %l:%M %p') %>
    <% else %>
      <%= task.deadline.strftime('%b %d %Y %l:%M %p') %>
    <% end %>
  </div>
   <div class="card-body">
     <h5 class="card-title"><%= task.name %><br></h5>
    <p class="card-text"><%= task.body %><br></p>
    <%= link_to "", task, class:"bi bi-info-circle h4" %>

  </div>

</div>

app/views/tasks/edit.html.erb
<h1>Editing task</h1>

<%= render "form", task: @task %>

<br>

<div>
  <%= link_to "Show this task", @task %> |
  <%#= link_to "Back to tasks", tasks_path %>
  <%= link_to "Back to Journal", categories_path %>
</div>

app/views/tasks/index.html.erb
<h1 class="display-6">Tasks</h1>
<div id="tasks">
<br>
  <div class="container d-flex justify-content-evenly flex-wrap">
  <% @tasks.each do |task| %>
    <% @categories.each do |category| %>
      <% if task.category_id == category.id %>
        <div class="card bg-light mb-3 ms-2" style="width: 250px;">
          <%= render task %>
        </div>
      <% end %>
    <% end %>
  <% end %>
  </div>
</div>
<br>
<%= link_to "New task", new_task_path, class:"btn btn-outline-primary" %>

app/views/tasks/new.html.erb
<h1 class="display-6">New task</h1>

<%= render "form", task: @task %>

<br>

app/views/tasks/show.html.erb
<div class="container">
<br>
<div class="border-primary card mb-3">
  <%= render @task %>
</div>

<div>
  <%= link_to "Edit", edit_task_path(@task), class:"btn btn-primary" %>
 
  <%#= link_to "Back to tasks", tasks_path %>

  <%= button_to "Delete", @task, method: :delete, class:"btn btn-warning mt-1" %>
</div>
</div>